// GENERATED by tools/build-anatomy.mjs — do not edit.
//
// The rig's bind pose, in the same app space as the model: metres, Y-up,
// +Z anterior, +X the figure's left, feet on y=0. Rebuild with:
//   npm run build:anatomy

import type { BoneName } from '../scene/rig'

/** Bone -> parent, null for the root. */
export const BONE_PARENT: Record<BoneName, BoneName | null> = {
  hips: null,
  spine: 'hips',
  chest: 'spine',
  neck: 'chest',
  head: 'neck',
  shoulder_L: 'chest',
  upperArm_L: 'shoulder_L',
  forearm_L: 'upperArm_L',
  hand_L: 'forearm_L',
  shoulder_R: 'chest',
  upperArm_R: 'shoulder_R',
  forearm_R: 'upperArm_R',
  hand_R: 'forearm_R',
  thigh_L: 'hips',
  shin_L: 'thigh_L',
  foot_L: 'shin_L',
  thigh_R: 'hips',
  shin_R: 'thigh_R',
  foot_R: 'shin_R',
}

/** Bone -> WORLD position at bind pose. */
export const BONE_REST: Record<BoneName, readonly [number, number, number]> = {
  hips: [-0.00014, 0.91596, 0.07231],
  spine: [-0.00128, 1.06338, 0.06753],
  chest: [-0.00118, 1.26288, 0.02935],
  neck: [-0.00011, 1.45164, 0.06651],
  head: [-0.00089, 1.54414, 0.06845],
  shoulder_L: [0.00838, 1.39248, 0.12984],
  upperArm_L: [0.16584, 1.40484, 0.07686],
  forearm_L: [0.20517, 1.10717, 0.07025],
  hand_L: [0.27495, 0.88015, 0.11665],
  shoulder_R: [-0.00966, 1.39063, 0.12866],
  upperArm_R: [-0.16739, 1.40443, 0.07668],
  forearm_R: [-0.20498, 1.10702, 0.07001],
  hand_R: [-0.27442, 0.87977, 0.11700],
  thigh_L: [0.08680, 0.90057, 0.07782],
  shin_L: [0.06820, 0.44580, 0.07659],
  foot_L: [0.05473, 0.07100, 0.07859],
  thigh_R: [-0.08725, 0.89955, 0.07901],
  shin_R: [-0.06931, 0.44633, 0.07748],
  foot_R: [-0.05368, 0.07105, 0.07820],
}

/** Bone -> translation relative to its parent, i.e. what the glTF node holds. */
export const BONE_LOCAL: Record<BoneName, readonly [number, number, number]> = {
  hips: [-0.00014, 0.91596, 0.07231],
  spine: [-0.00114, 0.14742, -0.00478],
  chest: [0.00010, 0.19950, -0.03818],
  neck: [0.00107, 0.18876, 0.03716],
  head: [-0.00078, 0.09250, 0.00195],
  shoulder_L: [0.00956, 0.12960, 0.10048],
  upperArm_L: [0.15746, 0.01236, -0.05298],
  forearm_L: [0.03934, -0.29768, -0.00661],
  hand_L: [0.06978, -0.22702, 0.04640],
  shoulder_R: [-0.00848, 0.12775, 0.09931],
  upperArm_R: [-0.15773, 0.01380, -0.05198],
  forearm_R: [-0.03759, -0.29741, -0.00667],
  hand_R: [-0.06944, -0.22726, 0.04699],
  thigh_L: [0.08694, -0.01539, 0.00551],
  shin_L: [-0.01859, -0.45477, -0.00123],
  foot_L: [-0.01347, -0.37481, 0.00201],
  thigh_R: [-0.08711, -0.01641, 0.00670],
  shin_R: [0.01794, -0.45322, -0.00152],
  foot_R: [0.01563, -0.37528, 0.00072],
}
